pragma solidity 0.6.11;
//SPDX-License-Identifier: MIT

import "hardhat/console.sol";
import "./Verifier.sol";

contract ZKVoting {
    // Events
    event AddLeaf(
        uint256 indexed key,
        uint256 indexed value,
        uint256 indexed oldRoot
    );
    event CreateVote(uint256 indexed voteId, uint256 indexed deadline);

    // Merkle Tree variables
    uint256 public root; // current root of the merkle tree
    uint256[] public leafValues; //  array of the tree's leaves, so anybody can reconstruct the merkle tree and generate proofs
    uint256 public nextKey; //  index in the merkle tree - the voter ID
    uint256 public proposalCounter = 1; // counter used to assign unique voteIds to vote campaigns

    mapping(uint256 => bool) public voteLogged; // used to log the unique hash generated by the circuit described above
    mapping(uint256 => string) public campaignName; // name of voting proposal
    mapping(uint256 => int256) public positiveVoteResult; // tracks the number of positive votes for a voteId
    mapping(uint256 => int256) public negativeVoteResult; // tracks the number of negative votes for a voteId
    mapping(uint256 => uint256) public voteDeadline; // timestamp at which voting for the specified voteId will be closed
    mapping(address => bool) private registeredAddress; // prevent duplicate wallet registration

    function getLeaves() public view returns (uint256[] memory) {
        return leafValues;
    }

    function createProposal(
        uint256 deadline,
        string calldata nameOfVote
    ) external {
        require(deadline > block.timestamp, "createProposal: Invalid Deadline");
        uint256 id = proposalCounter;
        campaignName[id] = nameOfVote;
        proposalCounter++;
        voteDeadline[id] = deadline;

        emit CreateVote(id, deadline);
    }

    function addLeaf(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[6] memory input
    ) external {
        require(input[1] == root, "addLeaf: Invalid Root");
        require(input[2] == nextKey, "addLeaf: Invalid Key");
        require(
            registeredAddress[msg.sender] == false,
            "addLeaf: Wallet already registered"
        );
        require(
            Verifier.verifyAdd2TreeProof(a, b, c, input) == true,
            "addLeaf: Invalid Proof"
        );

        leafValues.push(input[3]);
        nextKey = leafValues.length;
        root = input[0];
        registeredAddress[msg.sender] = true;

        emit AddLeaf(input[2], input[3], input[1]);
    }

    function proveLeaf(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[3] memory input,
        bool vote // bool determining if we will vote positively or negatively towards the voteId provided by the proof
    ) external returns (bool r) {
        require(voteLogged[input[0]] != true, "proveMembership: Vote Logged");
        require(
            voteDeadline[input[2]] > block.timestamp,
            "proveMembership: Deadline Passed"
        );
        require(input[1] == root, "proveMembership: Invalid Root");

        r = Verifier.verifyProveInTreeProof(a, b, c, input);
        require(r == true, "proveMembership: Invalid Proof");

        voteLogged[input[0]] = true;

        if (vote == true) {
            positiveVoteResult[input[2]] += 1;
        } else {
            negativeVoteResult[input[2]] += 1;
        }
    }
}
